# SPDX-License-Identifier: Proprietary
# Copyright © 2025 Shahin - All Rights Reserved
# Software-AI: AI-Powered Windows Control System

"""
Workflow Engine - Execute multi-step execution plans with dependency resolution.

Orchestrates the end-to-end execution of an ExecutionPlan generated by
PlanGenerator, validated by PlanValidator, and tracked by StepTracker.
Handles step dependencies, failure recovery, and parallel execution.
"""

from __future__ import annotations

import asyncio
import logging
import time
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional

from core.plan_generator import ExecutionPlan, ExecutionStep, ExecutionMode, StepType
from core.plan_validator import PlanValidator, ValidationLevel, ValidationStatus
from core.step_tracker import StepTracker, StepStatus

logger = logging.getLogger(__name__)


@dataclass
class WorkflowResult:
    """Result of executing an entire workflow."""
    plan_id: str
    success: bool
    total_steps: int
    completed_steps: int
    failed_steps: int
    skipped_steps: int
    elapsed_ms: float
    step_results: List[Dict[str, Any]] = field(default_factory=list)
    error_summary: str = ""
    validation_warnings: List[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "plan_id": self.plan_id,
            "success": self.success,
            "total_steps": self.total_steps,
            "completed_steps": self.completed_steps,
            "failed_steps": self.failed_steps,
            "skipped_steps": self.skipped_steps,
            "elapsed_ms": round(self.elapsed_ms, 2),
            "error_summary": self.error_summary,
            "validation_warnings": self.validation_warnings,
            "step_results": self.step_results,
        }


class WorkflowEngine:
    """Execute multi-step execution plans with dependency resolution.

    Usage:
        engine = WorkflowEngine(tool_executor=tool_executor)
        result = await engine.execute(plan)
        print(result.success, result.completed_steps)
    """

    def __init__(
        self,
        tool_executor: Any,
        ai_brain: Any = None,
        validate_before_execute: bool = True,
        max_retries_per_step: int = 2,
        fail_fast: bool = False,
    ):
        self.tool_executor = tool_executor
        self.ai_brain = ai_brain
        self.validate_before_execute = validate_before_execute
        self.max_retries_per_step = max_retries_per_step
        self.fail_fast = fail_fast
        self.validator = PlanValidator(ai_brain=ai_brain) if validate_before_execute else None

        logger.info(
            "WorkflowEngine initialized (validate=%s, max_retries=%d, fail_fast=%s)",
            validate_before_execute, max_retries_per_step, fail_fast,
        )

    async def execute(
        self,
        plan: ExecutionPlan,
        on_step_complete: Optional[Callable[[Dict[str, Any]], None]] = None,
    ) -> WorkflowResult:
        """Execute an entire workflow plan.

        Args:
            plan: The ExecutionPlan to execute.
            on_step_complete: Optional callback invoked after each step completes.

        Returns:
            WorkflowResult with execution summary.
        """
        start_time = time.monotonic()
        tracker = StepTracker(
            plan_id=plan.plan_id,
            total_steps=len(plan.steps),
            description=plan.description,
        )
        tracker.start()

        validation_warnings: List[str] = []

        # Validate before executing
        if self.validator:
            try:
                validation_warnings = await self._validate_plan(plan)
                if validation_warnings is False:
                    # Plan is invalid - abort
                    tracker.finish()
                    elapsed = (time.monotonic() - start_time) * 1000
                    return WorkflowResult(
                        plan_id=plan.plan_id,
                        success=False,
                        total_steps=len(plan.steps),
                        completed_steps=0,
                        failed_steps=0,
                        skipped_steps=0,
                        elapsed_ms=elapsed,
                        error_summary="Plan validation failed",
                        validation_warnings=[],
                    )
            except Exception as e:
                logger.warning("Validation failed, proceeding anyway: %s", e)

        # Sort steps by order
        ordered_steps = sorted(plan.steps, key=lambda s: s.order)

        # Execute steps sequentially (respecting dependencies)
        for step in ordered_steps:
            # Check if dependencies are satisfied
            deps_met = self._dependencies_satisfied(step, tracker)
            if not deps_met:
                logger.warning(
                    "Skipping step %s: dependencies not met (%s)",
                    step.step_id, step.dependencies,
                )
                tracker.skip_step(step.step_id, "Dependencies not met")
                continue

            # Execute with retries
            success = await self._execute_step_with_retries(step, tracker)

            if on_step_complete:
                try:
                    on_step_complete({
                        "step_id": step.step_id,
                        "order": step.order,
                        "action": step.action,
                        "success": success,
                    })
                except Exception as e:
                    logger.warning("Step callback failed: %s", e)

            if not success and self.fail_fast:
                # Skip remaining steps
                remaining = [s for s in ordered_steps if s.step_id not in
                            {r.step_id for r in tracker.results}]
                for s in remaining:
                    tracker.skip_step(s.step_id, "Aborted due to fail_fast")
                break

        tracker.finish()

        elapsed = (time.monotonic() - start_time) * 1000
        summary = tracker.get_summary()

        # Build error summary
        failed = tracker.get_failed_steps()
        error_summary = ""
        if failed:
            errors = [f"Step '{r.step_id}': {r.error}" for r in failed if r.error]
            error_summary = "; ".join(errors[:3])
            if len(failed) > 3:
                error_summary += f" (+{len(failed)-3} more)"

        result = WorkflowResult(
            plan_id=plan.plan_id,
            success=not tracker.has_failures,
            total_steps=summary["total_steps"],
            completed_steps=summary["completed"],
            failed_steps=summary["failed"],
            skipped_steps=summary["skipped"],
            elapsed_ms=elapsed,
            step_results=summary["steps"],
            error_summary=error_summary,
            validation_warnings=validation_warnings if isinstance(validation_warnings, list) else [],
        )

        logger.info(
            "Workflow %s completed: %d/%d steps OK (%.0fms)",
            plan.plan_id, result.completed_steps, result.total_steps, elapsed,
        )

        return result

    async def _validate_plan(self, plan: ExecutionPlan) -> Any:
        """Validate a plan before execution. Returns warnings list or False if invalid."""
        try:
            report = await self.validator.validate(
                plan,
                intent=plan.intent,
                level=ValidationLevel.BASIC,
                check_resources=False,
                check_security=True,
            )
            if not report.is_valid:
                logger.error("Plan validation failed: %s", report.status.value)
                return False
            return report.suggestions
        except Exception as e:
            logger.warning("Plan validation error: %s", e)
            return []

    def _dependencies_satisfied(self, step: ExecutionStep, tracker: StepTracker) -> bool:
        """Check if all dependencies of a step have succeeded."""
        if not step.dependencies:
            return True

        successful_ids = {
            r.step_id for r in tracker.results
            if r.status == StepStatus.SUCCESS
        }
        skipped_ids = {
            r.step_id for r in tracker.results
            if r.status == StepStatus.SKIPPED
        }

        for dep_id in step.dependencies:
            if dep_id not in successful_ids and dep_id not in skipped_ids:
                return False
        return True

    async def _execute_step_with_retries(
        self,
        step: ExecutionStep,
        tracker: StepTracker,
    ) -> bool:
        """Execute a step with retry logic."""
        tracker.start_step(step.step_id, step.order, step.action)

        last_error = ""
        max_attempts = min(step.retries, self.max_retries_per_step) + 1

        for attempt in range(1, max_attempts + 1):
            if attempt > 1:
                tracker.retry_step(step.step_id)
                logger.info(
                    "Retrying step %s (attempt %d/%d)",
                    step.step_id, attempt, max_attempts,
                )

            try:
                result = await self._execute_single_step(step)
                success = result.get("status") == "success"
                output = result.get("output", "")
                error = result.get("error", "")

                if success:
                    tracker.complete_step(step.step_id, output=output)
                    return True
                else:
                    last_error = error or "Step execution returned non-success status"

            except asyncio.TimeoutError:
                last_error = f"Step timed out after {step.timeout}s"
            except Exception as e:
                last_error = f"Execution error: {str(e)}"
                logger.warning(
                    "Step %s attempt %d failed: %s",
                    step.step_id, attempt, last_error,
                )

            # If not the last attempt, wait before retrying
            if attempt < max_attempts:
                wait_time = min(2 ** attempt, 10)  # Exponential backoff, max 10s
                await asyncio.sleep(wait_time)

        # All attempts failed
        tracker.fail_step(step.step_id, last_error)
        return False

    async def _execute_single_step(self, step: ExecutionStep) -> Dict[str, Any]:
        """Execute a single step by mapping it to a tool call."""
        tool_call = self._step_to_tool_call(step)

        if not tool_call:
            return {
                "status": "failed",
                "error": f"Cannot map step type '{step.step_type.value}' to a tool call",
            }

        try:
            results = await self.tool_executor.execute([tool_call])
            if results:
                return results[0]
            return {"status": "failed", "error": "No results returned"}
        except Exception as e:
            return {"status": "failed", "error": str(e)}

    def _step_to_tool_call(self, step: ExecutionStep) -> Optional[Dict[str, Any]]:
        """Map an ExecutionStep to a tool call dict compatible with ToolExecutor."""
        step_type = step.step_type
        action_lower = (step.action or "").lower()
        action_en = (step.action_en or "").lower()
        target = step.target or ""
        params = step.parameters or {}

        # ACQUIRE / PROCESS: use execute_command or list_directory
        if step_type in (StepType.ACQUIRE, StepType.PROCESS):
            # Try to build a meaningful command
            if "drive" in action_en or "drive" in action_lower:
                return {
                    "tool": "list_directory",
                    "params": {"path": target or "."},
                    "description": step.action,
                }
            return {
                "tool": "execute_command",
                "params": {"command": step.action_en or step.action},
                "description": step.action,
            }

        # OPEN: launch app or open file
        if step_type == StepType.OPEN:
            if target and (target.endswith(".exe") or "." not in target.split("/")[-1]):
                return {
                    "tool": "launch_app",
                    "params": {"app_name": target},
                    "description": step.action,
                }
            return {
                "tool": "execute_command",
                "params": {"command": f'start "" "{target}"'},
                "description": step.action,
            }

        # INTERACT: type, click, hotkey, or command
        if step_type == StepType.INTERACT:
            if "type" in action_en or "type" in action_lower:
                text = params.get("text", target)
                return {
                    "tool": "type_text",
                    "params": {"text": text},
                    "description": step.action,
                }
            if "click" in action_en or "click" in action_lower:
                return {
                    "tool": "click",
                    "params": {"target": target or params.get("target", "")},
                    "description": step.action,
                }
            if "hotkey" in action_en or "hotkey" in action_lower:
                keys = params.get("keys", [])
                if keys:
                    return {
                        "tool": "hotkey",
                        "params": {"keys": keys},
                        "description": step.action,
                    }
            # Generic: use execute_command with the English action text
            return {
                "tool": "execute_command",
                "params": {"command": step.action_en or step.action},
                "description": step.action,
            }

        # SAVE: write file
        if step_type == StepType.SAVE:
            file_path = params.get("file_path") or params.get("path", "")
            content = params.get("content", "")
            if file_path and content:
                # Use PowerShell to write file
                ps_cmd = (
                    f"powershell -NoProfile -Command "
                    f"Set-Content -Path '{file_path}' -Value @\"\n{content}\n\"@ -Encoding UTF8"
                )
                return {
                    "tool": "execute_command",
                    "params": {"command": ps_cmd},
                    "description": step.action,
                }
            return {
                "tool": "execute_command",
                "params": {"command": step.action_en or step.action},
                "description": step.action,
            }

        # VERIFY: verify with screen or execute check
        if step_type == StepType.VERIFY:
            return {
                "tool": "verify_action",
                "params": {"expected": step.action},
                "description": step.action,
            }

        # WAIT: wait
        if step_type == StepType.WAIT:
            wait_type = params.get("wait_type", "time")
            return {
                "tool": "wait",
                "params": {
                    "wait_type": wait_type,
                    "target": target,
                    "timeout": step.timeout,
                },
                "description": step.action,
            }

        # CLEANUP: generic command
        if step_type == StepType.CLEANUP:
            return {
                "tool": "execute_command",
                "params": {"command": step.action_en or step.action},
                "description": step.action,
            }

        # Fallback: execute_command
        return {
            "tool": "execute_command",
            "params": {"command": step.action_en or step.action},
            "description": step.action,
        }
